CREATE TABLE `setting` (
	`IDSETTING` SMALLINT(11) PRIMARY KEY  NOT NULL,
	`BACKGROUNDCOLOR` VARCHAR(70) NOT NULL,
	`BORDERCOLOR` VARCHAR(70) NOT NULL,
	`FONTCOLOR` VARCHAR(70) NOT NULL  
)ENGINE=INNODB;
INSERT INTO `setting` VALUES (1,"#ffffff","#a9a9a9","#000000");
INSERT INTO `setting` VALUES (2,"#000000","#ffffff","#ffffff");
CREATE TABLE `user`(
	`PSEUDO` VARCHAR(40) PRIMARY KEY NOT NULL,
	`MAIL` VARCHAR(100) NOT NULL,
	`PASSWORD` VARCHAR(100) NOT NULL,
	`LEVEL` SMALLINT(11) NOT NULL,
	`IDSETTING` SMALLINT DEFAULT 1 
)ENGINE=INNODB;
ALTER TABLE `user` ADD CONSTRAINT fk_IDSETTING FOREIGN KEY(`IDSETTING`) REFERENCES `setting`(`IDSETTING`);
INSERT INTO `user` VALUES ("Pieer","Pieer@MAIL","John",2,2);
INSERT INTO `user` VALUES ("Jack","Jack@MAIL","Kate",1,null);
INSERT INTO `user` VALUES ("Lena","Lena@MAIL","Lena",2,1);
CREATE TABLE `photo`(
	`IDPHOTO` SMALLINT(11) PRIMARY KEY NOT NULL,
	`SOURCE` VARCHAR(10000) NOT NULL,
	`LONGITUDE` DECIMAL NOT NULL,
	`LATITUDE` DECIMAL NOT NULL
)ENGINE=INNODB;
CREATE TABLE `post`(
	`IDPOST` SMALLINT(11) PRIMARY KEY NOT NULL,
	`PSEUDO` VARCHAR(40),
	`IDPHOTO` SMALLINT(11),
	FOREIGN KEY (`PSEUDO`) 
		REFERENCES user(`PSEUDO`)
		ON DELETE CASCADE ,
	FOREIGN KEY (`IDPHOTO`)
		REFERENCES photo(`IDPHOTO`)
		ON DELETE CASCADE 
)ENGINE=INNODB;
CREATE TABLE `comment`(
	`PSEUDO` VARCHAR(40),
	`IDPOST` SMALLINT(11),
	FOREIGN KEY (`PSEUDO`) 
		REFERENCES user(`PSEUDO`)
		ON DELETE CASCADE ,
	FOREIGN KEY (`IDPOST`)
		REFERENCES photo(`IDPHOTO`)
		ON DELETE CASCADE ,
	PRIMARY KEY(`PSEUDO`,`IDPOST`)
)ENGINE=INNODB;
